service: zoe-alexa-skill

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: prod
  timeout: 30
  memorySize: 128

functions:
  zoeGlucose:
    handler: handler.glucose
    events:
      - alexaSkill
